# Shopify App Configuration

name = "Product Importer Pro"
client_id = "d0f0ec29327c11fc4d6b093d6ecb77c0"

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://shopify-product-importer-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[build]
include_config_on_deploy = true
