# Shopify App Configuration

name = "Product Importer Pro"
client_id = "475c7b7c9d03b2e4ce2ef6216b15b5bd"

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://shopify-product-importer-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[build]
include_config_on_deploy = true
